site_name: "tinylogging"
repo_url: https://github.com/HamletSargsyan/tinylogging
edit_uri: blob/main/docs/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            show_root_heading: true
            # show_root_members_full_path: true
            # show_object_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: "source"
            group_by_category: true
            show_submodules: true
            relative_crossrefs: true
            scoped_crossrefs: true
            modernize_annotations: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_signature: true
            separate_signature: true
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: UTC
      locale: en
      type: timeago
      exclude:
        - index.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  features:
    - content.code.copy
    - navigation.instant
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
