[tool.poetry]
name = "tinylogging"
version = "2.0.0"
description = ""
authors = ["Hamlet <hamlets849@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/HamletSargsyan/tiny-logging"
homepage = "https://github.com/HamletSargsyan/tiny-logging"
keywords = ["logging"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers"
]

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.6"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.9"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
